### ISSUE TITLE
--parent and --format json don't play nice together

### ISSUE THREAD

**Issue by bebert64** [Mikescher/firefox-sync-client#10]
Hello,

Running `ffsclient bookmarks list --ignore-schema-errors --parent PARENT_ID` returns 5 different rows, but running `ffsclient bookmarks list --ignore-schema-errors --parent PARENT_ID --format json` returns 5 times the same element (one of the previous 5, seems to be always the same if I run the command several times in a row). `--format json` works fine on other commands not including the `--parent` argument.

**Comment by Mikescher** [comment]
yeah I can reproduce that. :(

Part of the problem is that `bookmarks list --format json` tries to build the hierachical bookmark tree (you can see that with a normal `bookmarks list --format json` call, you get the top-level bookmarks directly, and their children in the respective `children` arrays etc).  
But with `--parent` you only get the children of a single bookmark, but without their parent, so all bookmarks end up in the `unreferenced` array.

I don't know what your use case is, but perhaps you want to supply the `--linear` flag, to get a simple flat list of bookmarks, instead of the hierachical output.

But the fact that not all 5 bookmarks end up in `unreferenced` (but one bookmark 5 time) is definitely a bug and I will look into it (I have to see when I find time, perhaps this weekend).  
And at the same time I can perhaps look into a better behavior of `json` in combination with `--parent` (perhaps I simply also return the selected parent, then I have a root node where I can sort all other bookmarks under it).
